// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pepcvjymbczsjvqmhqnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlcGN2anltYmN6c2p2cW1ocW56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDE4NzUsImV4cCI6MjA3MTk3Nzg3NX0.oiEY3P1XoWbehszpUvpx1dYKd8TJs85tWoZ4HNreswA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});